recipe: default.v1
language: "id"

# -------------------------
# NLU Pipeline - External Service
# -------------------------
pipeline:
  - name: NLUCommandAdapter
    url: "http://localhost:3000"

# -------------------------
# Dialogue Policies - Simple (No TEDPolicy)
# -------------------------
policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.3
    core_fallback_action_name: "action_default_fallback"

assistant_id: pascasarjana-its-chatbot
